import { previewForLine } from "./utils.js";

function stripPromptEcho(before: string, completion: string): string {
  let out = completion;

  if (out.startsWith(before)) {
    out = out.slice(before.length);
  }

  const leadingWhitespace = out.match(/^\s+/)?.[0] ?? "";
  if (leadingWhitespace && out.slice(leadingWhitespace.length).startsWith(before)) {
    out = leadingWhitespace + out.slice(leadingWhitespace.length + before.length).replace(/^\s+/, "");
  }

  const maxOverlap = Math.min(before.length, out.length, 1000);

  for (let len = maxOverlap; len > 0; len--) {
    const beforeSuffix = before.slice(-len);
    const outPrefix = out.slice(0, len);

    if (beforeSuffix === outPrefix) {
      return out.slice(len);
    }
  }

  return out;
}

/**
 * Drops separator whitespace the buffer already contains.
 *
 * Models that are handed a right-trimmed prefix (see `trimLfmPrefillEnd`) emit the
 * separating space themselves, and models that are handed the untrimmed text sometimes
 * emit one anyway. Either way the space is already on screen, so keeping it would render
 * the ghost one column too far right.
 */
function alignLeadingWhitespace(before: string, completion: string): string {
  if (!/[ \t]$/.test(before)) return completion;
  return completion.replace(/^[ \t]+/, "");
}

/**
 * Keeps only the post-reasoning part of a response.
 *
 * Reasoning models (LFM2.5 always thinks before answering) can still open a think block
 * despite the pre-closed one in the prompt. Anything before `</think>` is reasoning, not
 * completion text.
 */
function stripThinkBlock(completion: string): string {
  const closing = completion.lastIndexOf("</think>");
  if (closing === -1) return completion;
  return completion.slice(closing + "</think>".length);
}

/**
 * Detects whether the generated text looks like an assistant's chat response
 * (such as apologies, conversational lead-ins, or questions) rather than a direct code continuation.
 *
 * @param text The cleaned candidate text.
 * @returns True if the text contains conversational chat cues.
 */
function looksLikeChatResponse(text: string): boolean {
  const s = text.trim();

  return [
    /^i understand\b/i,
    /^i'?m sorry\b/i,
    /^sorry\b/i,
    /^please provide\b/i,
    /^could you\b/i,
    /^can you\b/i,
    /^sure\b/i,
    /^certainly\b/i,
    /^here(?:'s| is)\b/i,
    /^as an ai\b/i,
    /^i don'?t have enough context\b/i,
    /^to assist\b/i,
    /^the continuation\b/i,
    /^suggested continuation\b/i,
    /^the next text\b/i,
    /^here(?:'s| is) the continuation\b/i,
    /^continuation:/i,
    /^output:/i,
    /^assistant:/i,
    // Reasoning leaking out of a thinking model, e.g. when `instruct` mode is forced
    // onto LFM2.5. Kept narrow on purpose: "the user can ..." is a plausible completion,
    // "the user wants ..." is how the model narrates a task to itself.
    /^the user (?:wants|wanted|asks|asked|says|said|is asking)\b/i,
    /^i'?ll continue\b/i,
  ].some((re) => re.test(s));
}

/**
 * Normalizes and cleans up the raw text generated by the autocomplete model.
 * 
 * It:
 * 1. Sanitizes line endings, drops any reasoning block, and removes model special tokens
 *    (e.g., FIM, chat, template and thinking tokens).
 * 2. Re-aligns leading whitespace against the text already in the buffer.
 * 3. Strips prompt echoes that the model may have repeated.
 * 4. Standardizes code structures (removes enclosing quotes, prefix continuation labels).
 * 5. Extracts only the first logical paragraph to prevent multi-paragraph block spam.
 * 6. Caps length at 200 characters to keep autocomplete completions concise.
 *
 * @param args The prefix context 'before' and the raw model output 'raw'.
 * @returns The cleaned up and truncated candidate completion.
 */
export function cleanupCompletion(args: { before: string; raw: string }): string {
  const { before } = args;

  let out = stripThinkBlock(args.raw.replace(/\r/g, ""))
    .replace(/<\|im_start\|>/g, "")
    .replace(/<\|im_end\|>/g, "")
    .replace(/<\|endoftext\|>/g, "")
    .replace(/<\|startoftext\|>/g, "")
    .replace(/<\|pad\|>/g, "")
    .replace(/<\|fim_prefix\|>/g, "")
    .replace(/<\|fim_suffix\|>/g, "")
    .replace(/<\|fim_middle\|>/g, "")
    .replace(/<\|tool_call_start\|>/g, "")
    .replace(/<\|tool_call_end\|>/g, "")
    .replace(/<\/?think>/g, "")
    .replace(/<start_of_turn>/g, "")
    .replace(/<end_of_turn>/g, "")
    .replace(/^\s*\n+/, "");

  out = alignLeadingWhitespace(before, out);
  out = stripPromptEcho(before, out);

  out = out
    .replace(/^["'`]+/, "")
    .replace(/["'`]+$/, "")
    .replace(
      /^(Completion:|Continuation:|Suggested continuation:|Output:|Assistant:|Text to append:)\s*/i,
      "",
    )
    .replace(/\s+$/g, "");

  out = stripPromptEcho(before, out);

  if (!out.trim()) return "";

  // Note: We do not discard looksLikeChatResponse immediately here, but rather let
  // getCompletionRejectionReason do it. This allows the debug logs to capture the
  // raw/clean text before rejecting it as "chat-like" rather than just "empty".

  // Extract only the first logical paragraph to avoid overwhelming the line preview.
  const firstParagraph = out.split(/\n\s*\n/)[0] ?? "";
  out = firstParagraph;

  if (out.length > 200) {
    out = out.slice(0, 200);
  }

  return out;
}

/**
 * Checks whether a cleaned completion should be displayed as a ghost preview.
 * 
 * @param completion The cleaned candidate completion.
 * @returns True if the completion is valid and should be shown.
 */
export function shouldShowCompletion(completion: string): boolean {
  return getCompletionRejectionReason(completion) === null;
}

/**
 * Inspects a cleaned-up completion candidate and determines why it should be
 * rejected.
 * 
 * @param completion The cleaned-up candidate completion.
 * @returns A string reason if the completion should be rejected, or null if it's acceptable to show.
 */
export function getCompletionRejectionReason(completion: string): string | null {
  const s = completion.trim();

  if (!s) return "empty";
  if (s.length < 2) return "too-short";
  
  // Reject model outputs that contain assistant meta-commentary, apologies, or conversational remarks.
  if (looksLikeChatResponse(s)) return "chat-like";

  // Prevent spamming too many lines/sentences in a single inline ghost prediction.
  const sentenceCount = (s.match(/[.!?]/g) ?? []).length;
  if (sentenceCount > 2) return "too-many-sentences";

  return null;
}

/**
 * Formats completion text safely into a single-line JSON string for debug logging.
 */
export function debugText(text: string): string {
  return JSON.stringify(previewForLine(text, 160));
}

export function takeNextChunk(s: string): { take: string; rest: string } {
  const match = s.match(/^(\s*)(\S+)/);

  if (!match) {
    return { take: s, rest: "" };
  }

  const take = match[1] + match[2];

  return {
    take,
    rest: s.slice(take.length),
  };
}

/**
 * Evaluates whether autocomplete ghost text should be suppressed based on the
 * current cursor-left context.
 *
 * It suppresses predictions if:
 * 1. The trimmed text is shorter than the configured minimum characters.
 * 2. The cursor is immediately typing a slash command, file path, or mention.
 * 3. The cursor is typing a token containing a slash (e.g. division `/`, relative paths `../`, `./`, `~/`, or URL structures),
 *    which helps avoid distracting or incorrect autocomplete suggestions in path/command-heavy states.
 *
 * @param text The text before the cursor.
 * @param minChars The minimum character threshold to trigger autocomplete.
 * @returns A string representing the suppression reason, or null if autocomplete is allowed.
 */
export function getGhostSuppressionReason(text: string, minChars: number): string | null {
  const trimmedLength = text.trim().length;
  if (trimmedLength < minChars) return `min-chars ${trimmedLength}/${minChars}`;

  const lastToken = text.split(/\s+/).at(-1) ?? "";
  if (lastToken.startsWith("/")) return "slash-command-or-path-token";
  if (lastToken.startsWith("@")) return "mention-token";
  if (text.endsWith("/")) return "path-like-trailing-slash";

  // Suppress if the last token contains a slash. This handles path-like prefixes
  // (e.g., "~/foo", "../bar", "./baz") as well as division or URL tokens.
  if (lastToken.includes("/")) return "slash-containing-token";

  return null;
}
